//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusReservationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusInfo
    {
        public int id { get; set; }
        public string BusNo { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string DepartureTime { get; set; }
        public string ArivalTime { get; set; }
        public string BusClass { get; set; }
        public Nullable<decimal> Fare { get; set; }
    }
}
